version: "3.3"

services:
  skiresort-api:
    container_name: skiresort-api
    restart: always
    image: node:20.19.0
    ports:
      - 4001:3000
    volumes:
      - ./:/usr/src/skiresort
      - skiresort-api-node-modules:/usr/src/skiresort/node_modules
      - skiresort-api-dist:/usr/src/skiresort/dist
    working_dir: /usr/src/skiresort
    environment:
      PORT_API: 3000

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: >-
      bash -c "set -e;
      npm install;
      npm run build:api;
      test -f dist/apps/skiresort-api/main.js;
      npm run start:prod"

  skiresort-batch:
    container_name: skiresort-batch
    restart: always
    image: node:20.19.0
    ports:
      - 4002:3001
    volumes:
      - ./:/usr/src/skiresort
      - skiresort-batch-node-modules:/usr/src/skiresort/node_modules
      - skiresort-batch-dist:/usr/src/skiresort/dist
    working_dir: /usr/src/skiresort
    environment:
      PORT_BATCH: 3001

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: >-
      bash -c "set -e;
      npm install;
      npm run build:batch;
      test -f dist/apps/skiresort-batch/main.js;
      npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge

volumes:
  skiresort-api-node-modules:
  skiresort-api-dist:
  skiresort-batch-node-modules:
  skiresort-batch-dist:
